#!/bin/bash


LOGDIR="$PWD/log"

MoveFiles() 
{
    local dir=$1
    sleep 3 # little hack for the script
    echo moving files now  "$(date)"
    mv $dir/* $INDIR/
}

if [ "$#" -eq 1 ]
then
    
    MoveFiles $1 &
fi

bin/fileconverter -alsologtostderr -log_dir $LOGDIR

